Documentation:
  Enabled: false

# Work around: if you run on single files like Gemfile you'll have snake_case
# error message
Style/FileName:
  Enabled: false

AllCops:
  # Include gemspec and Rakefile
  Include:
    - '**/*.gemspec'
    - '**/Rakefile'
